### ISSUE TITLE
cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by richard42** [mupen64plus/mupen64plus-user-issues#573]
Originally reported on Google Code with ID 574

```
Describe your system:
 - Operating System (be specific): Fedora 19 w/ Kernel 3.9.5-301
 - Machine type (32-bit or 64-bit): 64-bit
 - Mupen64Plus version: 2.0.0
 - Plugins used: None

Describe the problem:
Attempting to run emulator before installing a front-end, yet it can't seem to work.

Installation seemed to go off without a hitch, yet I get this error when trying to
start it.

[root@new-host-3 mupen64plus-bundle-linux64-2.0]# ./install.sh
Installing Mupen64Plus Binary Bundle to /usr/local
install: creating directory ‘/usr/local/share/mupen64plus’
install: creating directory ‘/usr/local/share/mupen64plus/doc’
install: creating directory ‘/usr/local/share/man/man6’
install: creating directory ‘/usr/local/lib/mupen64plus’
Installation successful.
[root@new-host-3 mupen64plus-bundle-linux64-2.0]# cd \
> 
[root@new-host-3 ~]# mupen64plus
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.0.0

UI-Console Error: dlopen('/usr/local/lib/libmupen64plus.so.2') failed: /usr/local/lib/libmupen64plus.so.2:
cannot open shared object file: No such file or directory
UI-Console Error: dlopen('./libmupen64plus.so.2') failed: ./libmupen64plus.so.2: cannot
open shared object file: No such file or directory
UI-Console Error: AttachCoreLib() Error: failed to find Mupen64Plus Core library
[root@new-host-3 ~]# 
```

Reported by `dylanlip` on 2013-08-29 12:24:28

**Comment by richard42** [comment]
```
Please provide the output of 

$ ls -ltr /usr/local/lib/libmupen64plus.so*
```

Reported by `sven@narfation.org` on 2013-08-29 12:37:17

**Comment by richard42** [comment]
```
-rw-r--r--. 1 root root 511816 Aug 29 08:08 /usr/local/lib/libmupen64plus.so.2.0.0
```

Reported by `dylanlip` on 2013-08-29 12:58:06

**Comment by richard42** [comment]
```
Can you please run as root:

/sbin/ldconfig -v

And please show the content of /etc/ld.so.conf.d/* and /etc/ld.so.conf
```

Reported by `sven@narfation.org` on 2013-08-29 13:34:23

**Comment by richard42** [comment]
```
For the files of /etc/ld.so.conf.d/*

atlas-x86_64.conf
/usr/lib64/atlas

kernel-3.10.7-200.fc19.x86_64.conf
# Placeholder file, no vDSO hwcap entries used in this kernel.

kernel-3.10.9-200.fc19.x86_64.conf
# Placeholder file, no vDSO hwcap entries used in this kernel.

kernel-3.9.5-301.fc19.x86_64.conf
# Placeholder file, no vDSO hwcap entries used in this kernel.

llvm-i386.conf
/usr/lib/llvm

llvm-x86_64.conf
/usr/lib64/llvm

mariadb-x86_64.conf
/usr/lib64/mysql

qt-i386.conf
/usr/lib/qt-3.3/lib

qt-x86_64.conf
/usr/lib64/qt-3.3/lib

wine-64.conf
/usr/lib64/wine/

xulrunner-64.conf
/usr/lib64/xulrunner

And then /etc/ld.so.conf

include ld.so.conf.d/*.conf

```

Reported by `dylanlip` on 2013-08-29 14:00:37

**Comment by richard42** [comment]
```
Ok, a file (example name "/etc/ld.so.conf.d/libc.conf") with following content is "missing":

/usr/local/lib


Please add such a file and rerun "/sbin/ldconfig"
```

Reported by `sven@narfation.org` on 2013-08-29 14:14:30

**Comment by richard42** [comment]
```
EVeyrthing works now. Thanks!
```

Reported by `dylanlip` on 2013-08-29 14:23:25

**Comment by richard42** [comment]
Reported by `sven@narfation.org` on 2013-08-29 14:30:16
- **Status changed**: `External`

**Comment by richard42** [comment]
```
After your modification i have the same issue :
LinuxMint # mupen64plus 
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.0.0

UI-Console Error: dlopen('/usr/local/lib/libmupen64plus.so.2') failed: libpng15.so.15:
cannot open shared object file: No such file or directory
UI-Console Error: dlopen('./libmupen64plus.so.2') failed: ./libmupen64plus.so.2: cannot
open shared object file: No such file or directory
UI-Console Error: AttachCoreLib() Error: failed to find Mupen64Plus Core library

LinuxMint # cat /etc/ld.so.conf.d/libc.conf
# libc default configuration
/usr/local/lib

Please Help !!!!


```

Reported by `p.mindesse` on 2014-05-24 08:36:35

**Comment by julyuz** [comment]
Is not there any other answer?, I followed the steps before mentioned, but I do not get that my mupen64plus works :( please help

**Comment by richard42** [comment]
This is a system configuration problem.  The root cause can be several different things.  I recommend opening a new issue ticket and posting the output from the terminal window when you try to run Mupen64Plus.

**Comment by julyuz** [comment]
Thanks for responding, and Iḿ sorry for not responding before (I had not have Internet :( ), when I try to run mupen64 from the terminal, I get this:

UI-Console Error: dlopen('/usr/local/lib/libmupen64plus.so.2') failed: libpng15.so.15: cannot open shared object file: No such file or directory
UI-Console Error: dlopen('./libmupen64plus.so.2') failed: ./libmupen64plus.so.2: cannot open shared object file: No such file or directory
UI-Console Error: AttachCoreLib() Error: failed to find Mupen64Plus Core library 

How can I get that library, or how can I install that library, if that my error was, thanks

**Comment by richard42** [comment]
What Linux distro are you running?  And what version of Mupen64Plus?

**Comment by iMonZ** [comment]
I have the same error and i run Ubuntu with the muppen64plus version 2.5.0
Error:
> Mupen64Plus Console User-Interface Version 2.5.0
UI-Console Error: dlopen('/usr/local/lib/libmupen64plus.so.2') failed: libpng12.so.0: cannot open shared object file: No such file or directory
UI-Console Error: dlopen('./libmupen64plus.so.2') failed: libpng12.so.0: cannot open shared object file: No such file or directory
UI-Console Error: AttachCoreLib() Error: failed to find Mupen64Plus Core library

**Comment by rastapopougros** [comment]
Same error too

**Comment by loganmc10** [comment]
You need to install libpng12. If your distro doesn't provide libpng12, you'll have to build mupen64plus yourself.

I build a linux64 version of mupen64plus here: https://m64p.github.io/ That is linked against libpng16, you can try that as well if you'd like.

**Comment by rastapopougros** [comment]
I already have libpng12 on Ubuntu 17.4…

I had a non-package version in a folder, and after I installed m64p via the distro package, and after via the PPA package which appeared to be more recent. And always same error in those 3 versions. I will not complile or build nothing just for playing an old game lol. I would wait until there was a package or other simple way which works again.

**Comment by loganmc10** [comment]
Ok sounds like you'll have to wait then

**Comment by rastapopougros** [comment]
Anyway, I dl your zip version and… it works! Thanks, my son will be happy tomorrow! :p

**Comment by ricardoberti** [comment]
Don't know if anyone of you done it work.
I had absolutely same error and fixed it this way:

1 - Install lipng12:
1.1 - Download from [https://packages.ubuntu.com/xenial/amd64/libpng12-0/download](https://packages.ubuntu.com/xenial/amd64/libpng12-0/download) (In my case, I have x64 linux, so I picked amd64 version)
1.2 - Install it with `sudo dpkg -i libpng12-0_1.2.54-1ubuntu1_amd64.deb` (Or whatever name of your download file)
2 - Create symbolic link to `libmupen64plus.so.2` with command
`sudo ln -s [your-folder]/mupen64plus/libmupen64plus.so.2 /usr/local/lib/libmupen64plus.so.2`

That's it! After this, just type `./mupen64plus rom-name-here.z64`

Hope it helps.
Regards

**Comment by WEEDSMOKENOT** [comment]
> Don't know if anyone of you done it work.
> I had absolutely same error and fixed it this way:
> 
> 1 - Install lipng12:
> 1.1 - Download from https://packages.ubuntu.com/xenial/amd64/libpng12-0/download (In my case, I have x64 linux, so I picked amd64 version)
> 1.2 - Install it with `sudo dpkg -i libpng12-0_1.2.54-1ubuntu1_amd64.deb` (Or whatever name of your download file)
> 2 - Create symbolic link to `libmupen64plus.so.2` with command
> `sudo ln -s [your-folder]/mupen64plus/libmupen64plus.so.2 /usr/local/lib/libmupen64plus.so.2`
> 
> That's it! After this, just type `./mupen64plus rom-name-here.z64`
> 
> Hope it helps.
> Regards

Sorry for necro but what do you mean by your folder

**Comment by WEEDSMOKENOT** [comment]
I will try to compile this shit again and see if that works. All I wanted to do was play golden eye.

**Comment by WEEDSMOKENOT** [comment]
I am necroing threads from 2015 to try and fix this. I have came to this point

**Comment by richard42** [comment]
If you compile from source you will not have this problem.. This only occurs when the machine that you are trying to run the emulator on has a different version of libpng than the machine which compiled the emulator.
