### ISSUE TITLE
mupen64plus-video-z64 can't compile

### ISSUE THREAD

**Issue by inukaze** [mupen64plus/mupen64plus-user-issues#658]
Hi there i can't compile , in the CLI , i saw the follow  

$ make all
    CC  _obj/osal_dynamiclib_unix.o
    CXX _obj/rgl.o
../../src/rgl.cpp:80:18: error fatal: glew.h:There is no such file or directory
completed compilation.
Makefile:394: failure instructions to the target '_obj/rgl.o'
make: **\* [_obj/rgl.o] Error 1

**Comment by inukaze** [comment]
I fix it , i just change 

#include <glew.h>

To

#include <GL/glew.h>

in the follow files : 
rgl.cpp
rgl_tiles.cpp
rgl_rendermodes.cpp

i saw "#include <GL/glew.h>" in "glshader.cpp" and now i can compile it :D

**Comment by samuelsantosdev** [comment]
Many thanks!
