### ISSUE TITLE
Missing health bars and power up icons in Kirby 64

### ISSUE THREAD

**Issue by GPDP2** [mupen64plus/mupen64plus-user-issues#659]
![Kirby](https://cloud.githubusercontent.com/assets/5431285/10803162/01d8aa64-7da8-11e5-8248-0add6e08c537.png)

This was first brought up in the libretro fork's issue tracker:

https://github.com/libretro/mupen64plus-libretro/issues/270

Seems like it's related to a commit that ported over RSP-related code from Project64, which fixed several Rare games in LLE.

Looking at the mupen64plus-core repo, said commit was selectively backported in https://github.com/mupen64plus/mupen64plus-core/commit/1125099cce6898cb9b39f5ba8cb7626dd983a18d. It is highly likely, then, that this issue was inherited from libretro through that commit.

This happens with every HLE and LLE video plugin and RSP plugin combination. A pull request with the intention of fixing the problem is here:

https://github.com/libretro/mupen64plus-libretro/pull/273

However, the furthest they got was fixing the problem with HLE, while LLE still has the issue. Only way of fully fixing it in both is fully reverting the earlier commit, which would once again break a bunch of Rare games with LLE.

**Comment by GPDP2** [comment]
This issue has been fixed in libretro by fully reverting the commit that brought code over from Project64, and instead applying the following commit:

https://github.com/libretro/mupen64plus-libretro/commit/ce3bcfad8dd20eb267dade9f52112fb8209171d2

With this, Kirby is fixed and Rare games (minus Perfect Dark) now work properly in LLE as well.

**Comment by richard42** [comment]
Thanks for the info guys, I have pushed the changes to fix this.
