### ISSUE TITLE
RSP plugin gone.

### ISSUE THREAD

**Issue by teayettle** [mupen64plus/mupen64plus-user-issues#679]
I just got up, and my RSP plugin is missing, I opened it and nothing was selectable, here's a picture:
![](https://cloud.githubusercontent.com/assets/23067288/19728451/41a9756a-9b48-11e6-97a2-b9b7bedc946c.jpg)

**Comment by Narann** [comment]
Is it physically here? I mean, in appdata/mupen64plus (IIRC)?

**Comment by ghost** [comment]
This doesn't look like mupen64plus. Was this reported to the wrong emulator project?

**Comment by richard42** [comment]
This is for the original "Mupen64" emulator.  The last release was over 10 years ago, it's not supported any more.
