### ISSUE TITLE
Star Wars racer problem: cannot boost

### ISSUE THREAD

**Issue by farinc** [mupen64plus/mupen64plus-user-issues#681]
The problem is that I cannot boost (turbo) while racing in-game. I am using a wiimote with nunchuk as my controller and all the controls work (like turning and braking) except I cannot boost. However if I use the keyboard I can boost.

So far I have used the InputAutoCfg.ini to do all my mapping for wiimote.
- I have lowered the var AnalogPeak (thinking the controller never reached peak)
- I have replaced the X and Y axis assignments with axis(num sign, num sign) with button(num, num) without success.
- I have even replaced the above assignments with key(num, num).

As in creating a uinput input with wiimote. I have used the following methods:
- wminput setup 
- moltengamepad setput (with xwiimote driver)

Both those methods register with mupen, but cant boost

Using a 64 arch machine with ubuntu 16.04. mupen64plus is latest build and all plugins.
Like I said, the keyboard works to boost. Has anyone else come across this problem with wiimotes?

**Comment by ScioNRankS** [comment]
so did you found any solution? im having the same issue, xbox360 controller and i´ve changed settings and so it seems like the analog don't reach peak. any admint?

**Comment by loganmc10** [comment]
This is likely the same problem as https://github.com/mupen64plus/mupen64plus-input-sdl/issues/46

We are waiting to hear from @richard42 about a solution

**Comment by farinc** [comment]
Thanks @loganmc10 for bringing up a solution to this problem. Definitely, this issue makes star wars racer near impossible to beat, or even play.

**Comment by richard42** [comment]
Hey can you please test again with the small change that I committed in mupen64plus-input-sdl cf02a74 ?

**Comment by farinc** [comment]
Sure I will get back to you about that. Right now I am a bit busy.

**Comment by farinc** [comment]
Sorry for the delay. Yes, now I can boost with a wiimote, commit `cf02a74` fixed the problem! I am happy to also report that other games do not appear affected by the fix in any negative way (MM, SSB, OOT).

Thanks @richard42
