### ISSUE TITLE
UI-Console Error

### ISSUE THREAD

**Issue by iMonZ** [mupen64plus/mupen64plus-user-issues#690]
I run Ubuntu with the muppen64plus version 2.5.0
and got this Error:
> Mupen64Plus Console User-Interface Version 2.5.0
    UI-Console Error: dlopen('/usr/local/lib/libmupen64plus.so.2') failed: libpng12.so.0: cannot open shared object file: No such file or directory
    UI-Console Error: dlopen('./libmupen64plus.so.2') failed: libpng12.so.0: cannot open shared object file: No such file or directory
    UI-Console Error: AttachCoreLib() Error: failed to find Mupen64Plus Core library

**Comment by richard42** [comment]
Check which version of libPNG you have installed. The special "-ubuntu" bundle is built against version 1.2. If you have a newer version of libPNG, then you can use one of the regular -linux64 bundles instead of the ubuntu one.
