### ISSUE TITLE
[macOS] Core Breaks Controller Paks

### ISSUE THREAD

**Issue by Joomla12** [mupen64plus/mupen64plus-user-issues#698]
Maybe someone can help me here, because I'm not sure if I'm doing something wrong during compilation, or if it's just a bug with the current state of the repo. Anyway, controller paks (memory, rumble, etc.) do not get detected by games that support them when I compile core myself. In the 2.5 release they work fine. I've done nothing special to compile, just installed the dependencies from Homebrew. It compiles without issue, and I only get a warning about libstdc++ being deprecated. I'm rather new to macOS (coming from 10 or so years with Linux), so I'm hoping someone will be able to tell me if I'm doing something wrong.

**Comment by bsmiles32** [comment]
Can you try explicitely specifying --datadir path_to_updated_repo/data when starting the emulator ?

Indeed the core now relies on pak specification found in mupen64plus.ini to initialize paks. If you don't specify anything, it will look in the default installed version location which does not contain such information, leading to controller pak breakage.

**Comment by Joomla12** [comment]
Awesome, thanks so much for the help.
