### ISSUE TITLE
How do I change the controls?

### ISSUE THREAD

**Issue by Video-Game-King** [mupen64plus/mupen64plus-user-issues#706]
Mupen64Plus has been giving me a lot of trouble control-wise, and I haven't been able to figure anything out. In theory, it's treating my controller (an ordinary Xbox 360 USB controller) as Controller (XBOX 360 For Windows), but aside from the console, all available evidence says it's really treating my controller like it's XInput. In any case, I've tried:

- Editing both settings in the InputAutoCfg file. Unfortunately, the changes never stick.
- Editing the controls in M64Py (this is how I found out Mupen64Plus was reading it as XInput). The changes I make here will stick, but only for as long as the window is open. Once I close it, I have to reconfigure the controls all over again. It doesn't help matters that configuring M64Py's controls is an incredibly fiddly process. The emulator's more likely to read a button press as an analog stick movement (axis(#)) than as the actual button press, so I have to keep pressing until it eventually does what I want it to. (Random inputs probably aren't to blame here. I'll keep analog sticks dead still, and the emulator waits for my input instead of jumping straight to analog movement.)
- Editing the mupen64plus.cfg file. For some reason, the controls only work when they're set to 2. Any other value, and the controls don't even register. This isn't the case when I change in the value in InputAutoCfg.

And it should go without saying, but I can't use the default controls. The C-buttons are mapped to the right analog stick but rotated 90 degrees counter-clockwise, B is mapped to X, and random C buttons are mapped to the face buttons.

**Comment by richard42** [comment]
There are 2 different ways to handle this. Do you want to always use the same controllers (hard code the configuration in mupen64plus.cfg), or do you want to have the option to use different controllers at different times, and just fix the auto-configuration?

**Comment by Video-Game-King** [comment]
I just finished editing that config file, and everything's working out now.
