### ISSUE TITLE
Problems with full screen (black bars) 

### ISSUE THREAD

**Issue by Turaltay** [mupen64plus/mupen64plus-user-issues#711]
Hi guys, i used to play my N64 games with Project64 till now. I wanted to try Mupen64plus because of better performance and accuracy, but i have some issues with black bars. I tried both graphic plugins, which are included in Mupen64plus, angrylion-plus and GlideN64. I made a picture with all settings which i tried (the game i used is Turok Rage Wars). As you can see, there is no setting where the black bars are removed. They only become narrower or wider. The only setting i needed to use in Project64 was the stretch setting in the graphics plugin (Glide64 Final 2012), which enabled me a fullscreen with no black bars in any game. Am i missing something or is it not possible to use this emulator without any black bars? My monitor resolution is 1920x1080. Hopefully someone can help me. 
![graphic-turok](https://user-images.githubusercontent.com/39458480/51772235-cc63b280-20eb-11e9-9668-9f4c4dd9b2cb.jpg)

**Comment by richard42** [comment]
What platform are you running on, and what version of Mupen64Plus and GlideN64 are you running?
I just tested by building from the current source code for both Mupen64Plus and the GlideN64 plugin, on 64-bit Gentoo Linux, with a 1920x1200 monitor in fullscreen mode, and GLideN64 will fill up the whole screen with no letterbox or pillarbox bars when I use either the Stretch or 16:9 aspect ratio settings.

**Comment by Turaltay** [comment]
I use a Windows 10 64-Bit host with the newest version of Mupen64Plus (build Jan 25 2019) and GlideN64. I have different results with different games. As example, i have no black bars with games like Mario Party or Pokemon Puzzle League. But games like Turok Rage Wars or Mario Tennis have them. Could you test if you have the same results with these games too?

**Comment by richard42** [comment]
Yes, with Turok Rage Wars there are black bars all around the image. I assume this is caused by the game itself, since other games fill up the whole screen.

**Comment by Turaltay** [comment]
But it works in Project64 with the Glide and the Jabo graphic plugin, as you can see here. Will this be improved in the future? Because as already mentioned, i would like to use Mupen64plus and not Project64.
![project64](https://user-images.githubusercontent.com/39458480/51798504-be10b600-2213-11e9-8365-d29d69d45551.png)

**Comment by loganmc10** [comment]
This is because of the graphics plugin (GLideN64). If you used GLideN64 with project64 you'd see the same thing. There is nothing that can be done in Mupen64Plus to fix it.
