### ISSUE TITLE
mupen64plus-video-rice fails to build Windows binary on case sensitive filesystems

### ISSUE THREAD

**Issue by ghost** [mupen64plus/mupen64plus-user-issues#719]
@Gillou68310

https://github.com/mupen64plus/mupen64plus-video-rice/commit/71fc6d7f7a2dd3da697f75bb1d03101f0a8f7be1#diff-57d4155f7bee41540d0a6cb6e3942f01R80 broke the build with case sensitive filesystems

        CXX _obj/OGLGraphicsContext.o
    In file included from ../../src/OGLCombiner.h:27:0,
                     from ../../src/DeviceBuilder.cpp:28:
    ../../src/osal_opengl.h:80:19: fatal error: GL/GL.h: No such file or directory
    compilation terminated.
    make: *** [Makefile:425: _obj/DeviceBuilder.o] Error 1
    make: *** Waiting for unfinished jobs....
    In file included from ../../src/OGLCombiner.h:27:0,
                     from ../../src/OGLCombiner.cpp:26:
    ../../src/osal_opengl.h:80:19: fatal error: GL/GL.h: No such file or directory
    compilation terminated.
    make: *** [Makefile:425: _obj/OGLCombiner.o] Error 1
    In file included from ../../src/OGLExtensions.cpp:22:0:
    ../../src/osal_opengl.h:80:19: fatal error: GL/GL.h: No such file or directory
    compilation terminated.
    In file included from ../../src/OGLGraphicsContext.cpp:24:0:
    ../../src/osal_opengl.h:80:19: fatal error: GL/GL.h: No such file or directory
    compilation terminated.
    make: *** [Makefile:425: _obj/OGLExtensions.o] Error 1
    make: *** [Makefile:425: _obj/OGLGraphicsContext.o] Error 1

The correct name of the file is GL/gl.h and not GL/GL.h

**Comment by Gillou68310** [comment]
Thanks I also changed it for glide64mk2

**Comment by Gillou68310** [comment]
https://github.com/mupen64plus/mupen64plus-video-rice/commit/677257a3110abc4a5ce2fa3dd7e58443c2cdc7a0
mupen64plus/mupen64plus-video-glide64mk2@3f76408
