### ISSUE TITLE
input-sdl: RCtrl+RShift axis slowdown insufficient for Banjo-Tooie

### ISSUE THREAD

**Issue by mgorny** [mupen64plus/mupen64plus-user-issues#727]
Banjo-Tooie has a few places where you have to tiptoe. However, even with RShift+RCtrl pressed the keystroke seem to move the axis too much. I had to increase the reduction by the value of 5 (i.e. `axis_max_val` became 15) to get Banjo to tiptoe.

**Comment by mgorny** [comment]
I did it this way:

```diff
diff --git a/src/plugin.c b/src/plugin.c
index 24aad8f..520567f 100644
--- a/src/plugin.c
+++ b/src/plugin.c
@@ -274,7 +274,7 @@ doSdlKeys(const unsigned char* keystate)
     if (keystate[SDL_SCANCODE_RCTRL])
         axis_max_val -= 40;
     if (keystate[SDL_SCANCODE_RSHIFT])
-        axis_max_val -= 20;
+        axis_max_val -= 25;
 
     for( c = 0; c < 4; c++ )
     {

**Comment by richard42** [comment]
https://github.com/mupen64plus/mupen64plus-input-sdl/pull/97 has been merged to fix this issue.
