### ISSUE TITLE
Video only displays at lower left corner

### ISSUE THREAD

**Issue by wn2000** [mupen64plus/mupen64plus-user-issues#728]
Running mupen64plus on a RK3328 aarch64 Linux, with SDL2, KMS/DRM, and GLES2.
There's no X11.
When starting with `--fullscreen --resolution 320x240` in a 1280x720 screen, I was expecting to see video rendered internally at 320x240 then scaled to 1280x720, but instead video is only rendered in a 320x240 block in the lower left corner of the 1280x720 screen, with the rest part being blank.
Is this the normal behavior? Any parameters I missed to make it full screen?
Tried both Rice and GLidemk2 and got the same result.

**Comment by richard42** [comment]
Yeah this is normal.  If your monitor can't scale up lower resolutions, you need to run it at your native resolution.
