### ISSUE TITLE
Error extracting app data /android

### ISSUE THREAD

**Issue by LordVal81** [mupen64plus/mupen64plus-user-issues#741]
Everytime I'm starting a game (with or without Daijisho) the following message appears:
https://imgbb.com/TmGJv8h
Error extracting app data
Failed to add file /storage/emulated/0/mupen64plus-fz/GalleryCache/romInfoCache.cfg to file /data/user/0/org.mupen64plusae.v3.fzurita.pro/files/romInfoCache.cfg
I installed everything new, but it's still on.

**Comment by richard42** [comment]
Sounds like a problem with the android front-end. We don't maintain this app; you need to get in touch with the developer of mupen64plus-fz.
