### ISSUE TITLE
Relocation error 

### ISSUE THREAD

**Issue by wellinton-capixaba** [mupen64plus/mupen64plus-user-issues#745]
Hi. When trying to build mupen 2.5.9, I receive: 
`LD  libmupen64plus.so.2.0.0
/usr/bin/ld: _obj/device/r4300/x86_64/dyna_start.o: relocation R_X86_64_PC32 against undefined symbol `g_dev' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value.`

My building command it is:

`PATH=$PATH:/media/34GB/Arquivos-de-Programas-Linux/Sdl-1.2.15/bin/:/media/34GB/Arquivos-de-Programas-Linux/Nasm-2.13/bin/ CFLAGS=-I/media/34GB/Arquivos-de-Programas-Linux/xorg/X11-1.4.4/include/ PKG_CONFIG_PATH=/media/34GB/Arquivos-de-Programas-Linux/Zlib-1.2.11/lib/pkgconfig/:/media/34GB/Arquivos-de-Programas-Linux/Png-1.2.14/lib/pkgconfig/:/media/34GB/Arquivos-de-Programas-Linux/Freetype-2.3.2/lib/pkgconfig/:/media/34GB/Arquivos-de-Programas-Linux/Mesa-7.5.2/lib/pkgconfig/:/media/34GB/Arquivos-de-Programas-Linux/Drm-2.4.75/lib/pkgconfig/:/media/34GB/Arquivos-de-Programas-Linux/xorg/Xorgproto-2018.1/share/pkgconfig/ make all prefix=/media/34GB/Arquivos-de-Programas-Linux/Mupen64plus-core-2.5.9`

**Comment by richard42** [comment]
it looks like some kind of a problem with your build environment. it says "undefined symbol g_dev" but g_dev is defined in main.c. The first step would be to run make with the "V=1" option to print out the build command parameters, and make sure that "main.o" is included with the list of files in the link command.
